REVOKE EXECUTE ON FUNCTION public.decrypt_token(text, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.encrypt_token(text, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.credit_balance(bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.deduct_balance(bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.platform_credit_balance(bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.platform_deduct_balance(bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.shop_credit_balance(uuid, bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.shop_deduct_balance(uuid, bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.reserve_inventory(uuid, integer, uuid) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.reserve_shop_inventory(uuid, integer, uuid) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.platform_admin_create_referral_payout(bigint, numeric, bigint, text, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.platform_credit_referral_for_subscription(uuid, bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.shop_credit_referral_for_order(uuid, uuid, bigint, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.increment_promo_usage(text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.increment_shop_promo_usage(uuid, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.increment_platform_promo_usage(uuid, bigint, uuid, numeric) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.ensure_shop_customer(uuid, bigint, text, text, text, boolean, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.has_entitlement(bigint, text) FROM anon, authenticated, public;
REVOKE EXECUTE ON FUNCTION public.is_shop_active(uuid) FROM anon, authenticated, public;

GRANT EXECUTE ON FUNCTION public.decrypt_token(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.encrypt_token(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.credit_balance(bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.deduct_balance(bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.platform_credit_balance(bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.platform_deduct_balance(bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.shop_credit_balance(uuid, bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.shop_deduct_balance(uuid, bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_inventory(uuid, integer, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.reserve_shop_inventory(uuid, integer, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.platform_admin_create_referral_payout(bigint, numeric, bigint, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.platform_credit_referral_for_subscription(uuid, bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.shop_credit_referral_for_order(uuid, uuid, bigint, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_promo_usage(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_shop_promo_usage(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.increment_platform_promo_usage(uuid, bigint, uuid, numeric) TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_shop_customer(uuid, bigint, text, text, text, boolean, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.has_entitlement(bigint, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_shop_active(uuid) TO service_role;

GRANT EXECUTE ON FUNCTION public.check_shop_payments_configured(uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.shop_has_premium_features(uuid) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validate_promo_code(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validate_shop_promo_code(uuid, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.validate_platform_subscription_promo(text, bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_shop_ai_avatar_quota(uuid) TO anon, authenticated, service_role;